### ISSUE TITLE
Pretty dull README!

### ISSUE THREAD

**Issue by benbacardi** [mikebryant/django-activity-stream-autoactor#3]

**Comment by justquick** [comment]
yea, what does this do?

**Comment by benbacardi** [comment]
Yeah, the README definitely needs work!

It's designed to work with [django-activity-stream](https://github.com/justquick/django-activity-stream). If you use `utils.action_send` from this package instead of `action.send` from `actstream`, it'll automatically populate the `actor` field of the action with `request.user`.

This is handy because you can call it from anywhere in your code, even places that don't normally have access to the `request` object (model methods, for example) - correctly setting the actor of that action to the logged in user, without having to pass the user or the request object all over the place.

**Comment by mikebryant** [comment]
@benbacardi Can you review #4 please?
